# Project metadata
sonar.projectKey=SSSKLv2_Frontend
sonar.organization=ricardotill

# Paths to sources and tests
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.spec.ts
sonar.exclusions=node_modules/**, dist/**, .angular/**, src/**/*.spec.ts, src/test-setup.ts

# Coverage reporting
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Encoding
sonar.sourceEncoding=UTF-8
