import { Injectable, signal, computed } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class LanguageService {
  // Current language - defaulting to Dutch as requested
  language = signal<'nl' | 'en'>('nl');

  // Centralized Dutch translations
  private readonly dutchTranslations = {
    // General
    'success': 'Succes',
    'error': 'Fout',
    'confirm': 'Bevestigen',
    'cancel': 'Annuleren',
    'save': 'Opslaan',
    'delete': 'Verwijderen',
    'refresh': 'Vernieuwen',
    'loading': 'Laden...',
    'actions': 'Acties',
    'edit': 'Bewerken',
    'never': 'Nooit',

    // Layout
    'welcome': 'Welkom',
    'login': 'Inloggen',
    'register': 'Registreren',
    'logout': 'Uitloggen',
    'main': 'Hoofdmenu',
    'homepage': 'Home',
    'about': 'Over',
    'user': 'Gebruiker',
    'general': 'Algemeen',
    'my_orders': 'Mijn Bestellingen',
    'my_saldo': 'Mijn Saldo',
    'settings': 'Instellingen',
    'admin': 'Administratie',
    'users': 'Gebruikers',
    'user_overview': 'Saldolijst',
    'products': 'Producten',
    'announcements': 'Mededelingen',
    'top_ups': 'Opwaarderingen',
    'orders': 'Bestellingen',
    'pos': 'Bestellen',
    'leaderboard': 'Leaderboard',
    'passkey': 'Passkey',

    // POS
    'what': 'Wat',
    'who': 'Wie',
    'pay': 'Betalen',
    'split_bill': 'Rekening splitten?',
    'amount': 'Aantal',
    'order': 'Bestellen',
    'order_placed': 'Order geplaatst!',
    'order_failed': 'Bestelling mislukt',
    'load_failed': 'Laden van gegevens mislukt',

    // Orders
    'date': 'Datum',
    'product': 'Product',
    'price': 'Prijs',
    'no_orders': 'Geen bestellingen gevonden.',
    'export_csv': 'CSV',
    'confirm_export_csv_title': 'Exporteren Bevestigen',
    'confirm_export_csv_message': 'Weet je zeker dat je alle bestellingen wilt exporteren naar een CSV-bestand?',
    'confirm_delete_order': 'Weet je zeker dat je deze bestelling voor {product} wilt verwijderen? Dit kan niet ongedaan worden gemaakt.',
    'confirm_delete_title': 'Verwijdering Bevestigen',
    'order_deleted': 'Bestelling succesvol verwijderd',
    'showing_orders_report': 'Bestellingen {first} t/m {last} van {total}',
    'showing_orders_report_no_total': 'Bestellingen {first} t/m {last}',
    'total_users': 'Totaal Gebruikers',
    'revenue': 'Omzet',
    'active_sessions': 'Actieve Sessies',
    'admin_orders': 'Bestellingen',
    'admin_orders_desc': 'Beheer hier alle systeembestellingen.',
    'announcements_desc': 'Beheer hier de mededelingen.',
    'products_desc': 'Beheer hier de producten.',
    'add_product': 'Product Toevoegen',
    'edit_product': 'Product Bewerken',
    'product_name': 'Productnaam',
    'product_description': 'Omschrijving',
    'view_livedisplay': 'Live Display Bekijken',
    'stock': 'Voorraad',
    'product_added': 'Product succesvol toegevoegd',
    'product_updated': 'Product succesvol bijgewerkt',
    'product_deleted': 'Product succesvol verwijderd',
    'confirm_delete_product': 'Weet je zeker dat je product {name} wilt verwijderen? Dit kan niet ongedaan worden gemaakt.',
    'no_products': 'Geen producten gevonden.',
    'enable_leaderboard': 'Leaderboard Inschakelen',
    'top_ups_desc': 'Beheer hier de opwaarderingen.',
    'no_top_ups': 'Geen opwaarderingen gevonden.',
    'showing_top_ups_report': 'Opwaarderingen {first} t/m {last} van {total}',
    'add_top_up': 'Opwaardering Toevoegen',
    'top_up_added': 'Opwaardering succesvol toegevoegd',
    'top_up_deleted': 'Opwaardering succesvol verwijderd',
    'confirm_delete_top_up': 'Weet je zeker dat je deze opwaardering wilt verwijderen?',
    'select_user': 'Selecteer Gebruiker',

    // Admin - Users
    'username': 'Gebruikersnaam',
    'name': 'Naam',
    'full_name': 'Volledige Naam',
    'balance': 'Saldo',
    'last_ordered': 'Laatst Besteld',
    'edit_user': 'Gebruiker Bewerken',
    'first_name': 'Voornaam',
    'last_name': 'Achternaam',
    'email_confirmed': 'E-mail Bevestigd',
    'phone_number': 'Telefoonnummer',
    'phone_number_confirmed': 'Telefoonnummer Bevestigd',
    'new_password_help': 'Nieuw wachtwoord (leeg laten om huidig te behouden)',
    'roles': 'Rollen',
    'select_roles': 'Selecteer Rollen',
    'user_updated': 'Gebruiker succesvol bijgewerkt',
    'update_failed': 'Bijwerken gebruiker mislukt',
    'confirm_delete_user': 'Weet je zeker dat je gebruiker {user} wilt verwijderen? Dit kan niet ongedaan worden gemaakt.',
    'user_deleted': 'Gebruiker succesvol verwijderd',
    'delete_failed': 'Verwijderen gebruiker mislukt',
    'no_users': 'Geen gebruikers gevonden.',
    'email': 'E-mail',
    'password_edit_desc': 'Nieuw wachtwoord (laat leeg om te behouden)',

    // Admin - Announcements
    'add_announcement': 'Mededeling Toevoegen',
    'edit_announcement': 'Mededeling Bewerken',
    'message': 'Bericht',
    'announcement_order': 'Volgorde',
    'is_scheduled': 'Ingepland',
    'planned_from': 'Gepland van',
    'planned_till': 'Gepland tot',
    'announcement_added': 'Mededeling succesvol toegevoegd',
    'announcement_updated': 'Mededeling succesvol bijgewerkt',
    'announcement_deleted': 'Mededeling succesvol verwijderd',
    'confirm_delete_announcement': 'Weet je zeker dat je deze mededeling wilt verwijderen? Dit kan niet ongedaan worden gemaakt.',
    'no_announcements': 'Geen mededelingen gevonden.',
    'global_settings': "Globale Instellingen",
    'global_settings_admin': "Globale Instellingen Beheer",
    'global_settings_updated': "Instellingen succesvol bijgewerkt",
    'global_settings_desc': "Beheer hier de globale instellingen van de applicatie, zoals de 'Wat is er nieuw?' modal.",
    'whats_new_settings_section_title': "'Wat is er nieuw?' Instellingen",
    'whats_new_settings_section_desc': "Voer hier de content in voor de 'Wat is er nieuw?' modal. Deze content wordt getoond aan gebruikers bij het inloggen.",
    'whats_new_modal_title': "Wat is er nieuw in SSSKL?",

    // Admin - Roles
    'roles_title': 'Rollen Beheren',
    'roles_add': 'Rol Toevoegen',
    'roles_id': 'ID',
    'roles_name': 'Naam',
    'roles_actions': 'Acties',
    'roles_delete': 'Verwijderen',
    'roles_no_roles': 'Geen rollen gevonden',
    'roles_add_role': 'Nieuwe Rol Aanmaken',
    'confirm_delete_role': 'Weet je zeker dat je de rol \'{role}\' wilt verwijderen?',
    'role_created': 'Rol aanmaken succesvol',
    'role_updated': 'Rol bijwerken succesvol',
    'role_creation_failed': 'Aanmaken rol mislukt',
    'role_deleted': 'Rol verwijderen succesvol',
    'role_deletion_failed': 'Verwijderen rol mislukt',
    'roles_edit_role': 'Rol Bewerken',
    'required': 'Verplicht',

    // Settings
    'user_settings': 'Gebruikersinstellingen',
    'profile': 'Profiel',
    'security': 'Accountbeveiliging',
    'tfa': '2FA Instellingen',
    'personal_data': 'Persoonlijke Gegevens',
    'no_roles': 'Geen rollen toegewezen',
    'color_mode': 'Website Kleurmodus',
    'color_mode_desc': "Kies hoe de website eruitziet. 'Auto' volgt je systeeminstellingen.",
    'save_changes': 'Wijzigingen Opslaan',
    'settings_updated': 'Je instellingen zijn bijgewerkt.',
    'settings_update_failed': 'Bijwerken van instellingen mislukt. Probeer het opnieuw.',
    'profile_picture': 'Profielfoto',
    'profile_picture_desc': 'Upload een foto om je profiel te personaliseren. We raden een vierkante afbeelding aan.',
    'change_picture': 'Foto Wijzigen',
    'crop_image': 'Foto Bijsnijden',

    // Settings - Security
    'email_status': 'Huidige Email Status',
    'confirmed': 'Bevestigd',
    'unconfirmed': 'Onbevestigd',
    'new_email': 'Nieuw E-mailadres',
    'email_placeholder': 'Laat leeg om huidig e-mailadres te behouden',
    'current_password': 'Huidig Wachtwoord',
    'password_placeholder': 'Vereist bij het wijzigen van je wachtwoord',
    'new_password': 'Nieuw Wachtwoord',
    'new_password_placeholder': 'Laat leeg om huidig wachtwoord te behouden',
    'update_security': 'Beveiliging Bijwerken',
    'security_updated': 'Je beveiligingsinstellingen zijn bijgewerkt.',
    'security_update_failed': 'Bijwerken van beveiligingsinstellingen mislukt. Controleer je invoer.',
    'passkeys_title': 'Passkeys',
    'passkeys_description': 'Beheer je passkeys om sneller en veiliger in te loggen.',
    'add_passkey': 'Passkey Toevoegen',
    'no_passkeys': 'Geen passkeys geregistreerd.',
    'passkey_registered': 'Passkey succesvol geregistreerd.',
    'passkey_deleted': 'Passkey succesvol verwijderd.',
    'confirm_delete_passkey': 'Weet je zeker dat je deze passkey wilt verwijderen?',
    'passkey_name': 'Passkey Naam',
    'passkey_name_placeholder': 'Bijv. Mijn iPhone, Werk Laptop',
    'enter_passkey_name': 'Voer een naam in voor je nieuwe passkey',

    // Settings - 2FA
    'enable_tfa': 'Tweestapsverificatie Inschakelen',
    'tfa_desc': 'Beveilig je account door 2FA in te schakelen. Open je authenticator app (zoals Google Authenticator of Authy) en scan de QR-code hieronder, of voer de gedeelde sleutel handmatig in.',
    'shared_key': 'Gedeelde Sleutel',
    'verify_code': 'Code Verifiëren',
    'digit_code': '6-cijferige code',
    'verify_enable': 'Verifiëren & Inschakelen',
    'tfa_enabled_title': 'Tweestapsverificatie is Ingeschakeld',
    'tfa_enabled_desc': 'Je account is beveiligd. Je hebt nog <strong>{count}</strong> herstelcodes over.',
    'save_recovery_codes': '⚠️ Bewaar deze herstelcodes',
    'recovery_codes_desc': 'Deze codes worden niet opnieuw getoond. Bewaar ze op een veilige plek zoals een wachtwoordmanager.',
    'disable_tfa': '2FA Uitschakelen',
    'reset_recovery': 'Herstelcodes Opnieuw Instellen',
    'tfa_success': 'Tweestapsverificatie succesvol ingeschakeld.',
    'tfa_failed': 'Inschakelen van 2FA mislukt. Controleer je code en probeer het opnieuw.',
    'tfa_disabled': 'Tweestapsverificatie uitgeschakeld.',
    'recovery_reset_success': 'Herstelcodes succesvol opnieuw ingesteld.',

    // Settings - Personal Data
    'download_data_title': 'Persoonlijke Gegevens Downloaden',
    'download_data_desc': 'Je kunt een kopie opvragen van je persoonlijke gegevens die aan je account zijn gekoppeld. Dit gedownloade bestand bevat alle informatie die we veilig over jou opslaan.',
    'download_btn': 'Mijn Gegevens Downloaden',
    'delete_account_title': 'Account Verwijderen',
    'delete_account_desc': 'Zodra je je account verwijdert, is er geen weg terug. Wees alsjeblieft zeker. Al je gegevens inclusief bestelgeschiedenis worden permanent verwijderd.',
    'delete_account_btn': 'Mijn Account Verwijderen',
    'confirm_delete_account': 'Weet je zeker dat je je account wilt verwijderen? Deze actie kan niet ongedaan worden gemaakt.',
    'confirm_delete_account_title': 'Accountverwijdering Bevestigen',
    'account_deleted': 'Je account is verwijderd.',

    // Leaderboard
    'select_product': 'Selecteer een product',
    'last_12_hours': 'Afgelopen 12 uur',
    'monthly': 'Maandelijks',
    'total': 'Totaal',
    'rank': 'Plek',
    'no_purchases_period': 'Er zijn deze periode geen aankopen gedaan. Dus ik zou zeggen, bestellen maar! ;)',
    'achievements': 'Achievements',
    'achievements_desc': 'Bekijk hier de behaalde achievements van alle gebruikers.',
    'no_achievements': 'Geen achievements gevonden voor deze gebruiker.',
    'achieved_on': 'Behaald op',
    'seen': 'Gezien',
    'not_seen': 'Nieuw',
    'locked': 'Vergrendeld',
    'not_achieved_yet': 'Nog niet behaald',
    'new_achievement': '🎉 Nieuwe Achievement{s}! 🎉',
    'new_achievement_desc': 'Je hebt zojuist nieuwe achievement(s) ontgrendeld!',
    'awesome': 'Geweldig!',
    'achievement_detail': 'Achievement Details',
    'earners': 'Behaald door',
    'no_earners': 'Niemand heeft dit achievement nog behaald.',
    'earned_by_count': 'Behaald door {count} gebruiker(s)',
    'earned_on': 'Behaald op',

    // Events
    'events': 'Evenementen',
    'event_details': 'Evenement Details',
    'create_event': 'Evenement Toevoegen',
    'edit_event': 'Evenement Bewerken',
    'title': 'Titel',
    'description': 'Omschrijving',
    'start_date': 'Startdatum',
    'end_date': 'Einddatum',
    'rsvp': 'Aanmelden',
    'accept': 'Aanwezig',
    'decline': 'Afwezig',
    'attendees': 'Deelnemers',
    'declined': 'Afgemeld',
    'no_events': 'Geen evenementen gevonden.',
    'no_events_desc': 'Blijf op de hoogte van alle geplande activiteiten!',
    'confirm_delete_event': 'Weet je zeker dat je dit evenement wilt verwijderen?',
    'past': 'Verstreken',
    'share': 'Delen',

    // Auth
    'back': 'Terug',
    'create_account': 'Account Aanmaken',
    'already_have_account': 'Heb je al een account?',
    'dont_have_account': 'Nog geen account?',
    'username_required': 'Gebruikersnaam is verplicht.',
    'password_required': 'Wachtwoord is verplicht.',
    'email_required': 'E-mail is verplicht.',
    'invalid_email': 'Voer een geldig e-mailadres in.',
    'first_name_required': 'Voornaam is verplicht.',
    'last_name_required': 'Achternaam is verplicht.',
    'remember_me': 'Onthoud mij',
    'tfa_code': 'Twee-factor authenticatiecode',
    'tfa_help': 'Open je authenticator-app en voer de code in.',
    'enter_tfa': 'Voer je 2FA-code in.',
    'invalid_tfa': 'Ongeldige 2FA-code.',
    'invalid_login': 'Ongeldige gebruikersnaam of wachtwoord.',
    'enter_username_first': 'Voer eerst je gebruikersnaam in.',
    'registration_successful': 'Registratie succesvol! Je wordt doorgestuurd naar de login...',
    'registration_failed': 'Registratie mislukt. Probeer het opnieuw.',
    'remove_profile_picture': 'Profielfoto Verwijderen',
    'confirm_remove_profile_picture': 'Weet je zeker dat je de profielfoto van deze gebruiker wilt verwijderen?',
    'profile_picture_removed': 'Profielfoto succesvol verwijderd',
    'password': 'Wachtwoord',
    'send_notification': 'Notificatie Verzenden',
    'notification_title': 'Titel',
    'notification_message': 'Bericht',
    'notification_link': 'Link (Optioneel)',
    'fan_out': 'Stuur naar iedereen (Fan-Out)',
    'select_users': 'Selecteer Gebruikers',
    'notification_sent_success': 'Notificatie is succesvol verzonden!',
    'admin_notifications': 'Notificaties Beheren',
    'notification_link_help': 'Optionele URL waar de gebruiker naartoe wordt gestuurd bij het klikken op de notificatie.',
    'push_notifications': 'Push Notificaties',
    'push_notifications_desc': 'Ontvang meldingen op je apparaat, ook als de website niet open staat.',
    'push_enabled': 'Ingeschakeld',
    'push_disabled': 'Uitgeschakeld',
    'push_unsupported': 'Niet ondersteund door je browser',
    
    // Push Dialog
    'PUSH.DIALOG.TITLE': 'Blijf op de hoogte!',
    'PUSH.DIALOG.HEADING': 'Push Notificaties',
    'PUSH.DIALOG.DESCRIPTION': 'Wil je meldingen ontvangen voor nieuwe reacties, mededelingen en behaalde achievements? Je kunt dit altijd weer uitzetten in de instellingen.',
    'PUSH.DIALOG.ENABLE': 'Inschakelen',
    'PUSH.DIALOG.LATER': 'Misschien later',
  };

  // Signal for getting translations
  t = computed(() => {
    // Return the concrete object to maintain type safety and avoid index signature lints
    return this.dutchTranslations;
  });

  constructor() { }

  // Basic translate function
  translate(key: keyof typeof this.dutchTranslations, params?: Record<string, string | number>): string {
    let text = this.dutchTranslations[key] || key;
    if (params) {
      Object.keys(params).forEach(p => {
        text = text.replace(`{${p}}`, params[p].toString());
      });
    }
    return text;
  }
}
